apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
  labels:
    app.kubernetes.io/component: letsencrypt-issuer
    app.kubernetes.io/part-of: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@kagchi.my.id
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
            serviceType: ClusterIP