apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cnf-app-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
spec:
  ingressClassName: nginx
  rules:
    - host: cnf-app.minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cnf-app-service
                port:
                  number: 3000