apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  namespace: production
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: production
roleRef:
  kind: Role
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
